  version: '3.8'

  services:
      php-apache-environment:
          image: suryey-web-native
          container_name: survey-web-app
          build:
              context: ./
              dockerfile: Dockerfile
          depends_on:
              - db
          volumes:
              - ./:/var/www/html/
          ports:
              - 8000:80
          networks:
              - backend
      db:
          container_name: db
          image: mysql
          command: --default-authentication-plugin=mysql_native_password
          restart: always
          environment:
              MYSQL_ROOT_PASSWORD: admin123
              MYSQL_DATABASE: survey
              MYSQL_USER: admin
              MYSQL_PASSWORD: password
              MYSQL_ROOT_HOST: '%'
          ports:
              - "3306:3306"
          volumes:
              - ./survey.sql:/docker-entrypoint-initdb.d/survey.sql
          networks:
              - backend

  volumes:
    db:

  networks:
    backend:
      name: backend-network
      ipam:
        driver: default
        config:
          - subnet: 172.21.0.0/24
